In [1]:
import matplotlib.pyplot as plt
import numpy as np


# Pauli Matrices

파울리 행렬의 아이겐밸류와 아이겐벡터를 구하시오.  

$$ s_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad
s_y = \begin{pmatrix} 0 & -j \\ j & 0 \end{pmatrix}, \quad
s_z  = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}. $$

In [2]:
s_x=np.array([[0,1],[1,0]])
s_y=np.array([[0,-1j],[1j,0]])
s_z=np.array([[1,0],[0,-1]])
eig_x=np.linalg.eig(s_x)
eig_y=np.linalg.eig(s_y)
eig_z=np.linalg.eig(s_z)
print(eig_x) # eigenvalue and eigenvector 
print(eig_y)
print(eig_z)

(array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))
(array([ 1.+0.j, -1.+0.j]), array([[-0.        -0.70710678j,  0.70710678+0.j        ],
       [ 0.70710678+0.j        ,  0.        -0.70710678j]]))
(array([ 1., -1.]), array([[1., 0.],
       [0., 1.]]))


# Normal Modes 

(고전역학 by Thornton & Marion 챕터 12.2 및 예제 12.3 참조)
용수철 상수가 $k$인 용수철에 연결된 두 개의 물체의 노말 모드를 구해보자. 두 개의 물체의 운동방정식은 다음으로 주어진다.
$$ -m w^2 x_1 = -2kx_1 +k x_2, \\
-m w^2 x_2 = k x_1 - 2 k x_2.$$
eigenfrequencies $w$는 다음의 행렬식을 통해 구할 수 있다.
$$ \frac{k}{m w^2} \begin{pmatrix} 2 & -1 \\ -1 & 2 \end{pmatrix} 
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix}=
\lambda \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} $$

In [3]:
# 위의 행렬의 고유값을 구하자.
coupled=np.array([[2,-1],[-1,2]])
eig_coupled=np.linalg.eig(coupled)
print(eig_coupled)

(array([3., 1.]), array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]]))


$$ \frac{\lambda_1mw^2}{k}=1 ,\frac{\lambda_2mw^2}{k}=3 $$
$$ \lambda_1=1, \lambda_2=3 $$

따라서 eigenfrequencies는
$$ w_1 = \sqrt{\frac{k}{m}}, \quad w_2 = \sqrt{\frac{3k}{m}}. $$

위에서 구한 아이겐벡터와 아이겐밸류의 의미를 설명하여라.

미분방정식의 해는 다음과 같은 형태를 따른다. $x(t)=ce^{iwt}$ (c는 상수이며 t로 두 번 미분할 경우 $ -mw^2x(t) $ 가 된다.)

위에서 구한 아이겐밸류에 의해 eigenfrequencies $w_1$ 과 $w_2$가 결정된다.
아이겐벡터의 각 성분  $x_1$ 과 $x_2$는 x(t)에서 앞에 상수 c이며 진폭을 의미한다. 

정리하자면, 주어진 상황에는 두 개의 모드가 있다.
$$1)w=w_1$$
$$x_1(t)=ce^{iw_1t}$$
$$x_2(t)=ce^{iw_1t}$$
$$2)w=w_2$$
$$x_1(t)=ce^{iw_2t}$$
$$x_2(t)=-ce^{iw_2t}$$
위에서 구한 대로 $w=w_2$ 에 해당하는 아이겐벡터의  $x_1,x_2$는 크기가 같고 부호가 반대이다. 즉, 두 물체가 가까워 졌다 멀어졌다를 반복하며 움직인다.